import { 
  User,
  Heart,
  Brain,
  Shield,
  Sword,
  Star,
  Target,
  Flame,
  Glasses,
  HandMetal,
  Crown,
  Laugh,
  Frown,
  Footprints,
  Hammer,
  Palette,
  Music,
  BookOpen,
  Coins,
  HeartCrack,
  Lightbulb,
  Compass
} from 'lucide-react';

export const attributeTypes = [
  { name: 'Physical Appearance', icon: User },
  { name: 'Personality Core', icon: Heart },
  { name: 'Intelligence', icon: Brain },
  { name: 'Defense Mechanism', icon: Shield },
  { name: 'Combat Style', icon: Sword },
  { name: 'Special Ability', icon: Star },
  { name: 'Life Goal', icon: Target },
  { name: 'Passion', icon: Flame },
  { name: 'Knowledge', icon: Glasses },
  { name: 'Skill', icon: HandMetal },
  { name: 'Status', icon: Crown },
  { name: 'Humor', icon: Laugh },
  { name: 'Fear', icon: Frown },
  { name: 'Movement Style', icon: Footprints },
  { name: 'Craft', icon: Hammer },
  { name: 'Artistic Ability', icon: Palette },
  { name: 'Musical Talent', icon: Music },
  { name: 'Education', icon: BookOpen },
  { name: 'Wealth', icon: Coins },
  { name: 'Emotional Wound', icon: HeartCrack },
  { name: 'Innovation', icon: Lightbulb },
  { name: 'Moral Compass', icon: Compass },
  { name: 'Background', icon: User },
  { name: 'Relationship', icon: Heart },
  { name: 'Occupation', icon: Brain }
];